//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAndAreaOfKnowLedge
    {
        public int IdBookAndAreaOfKnowLedge { get; set; }
        public int IdInstance { get; set; }
        public int IdAreaOfKnowLedge { get; set; }
    
        public virtual AreaOfKnowLedge AreaOfKnowLedge { get; set; }
        public virtual Instance Instance { get; set; }
    }
}
