//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instance()
        {
            this.BookAndAreaOfKnowLedge = new HashSet<BookAndAreaOfKnowLedge>();
            this.ReaderCardFile = new HashSet<ReaderCardFile>();
        }
    
        public int IdInstance { get; set; }
        public int IdBook { get; set; }
        public string UniqueChipher { get; set; }
        public string UniqueInventoryNumber { get; set; }
        public string PlacementLocation { get; set; }
    
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAndAreaOfKnowLedge> BookAndAreaOfKnowLedge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReaderCardFile> ReaderCardFile { get; set; }
    }
}
