//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MollaevYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reader()
        {
            this.ReaderCardFile = new HashSet<ReaderCardFile>();
        }
    
        public int IdReader { get; set; }
        public string UniqueNumberReaderCard { get; set; }
        public string LastNameReader { get; set; }
        public string FirstNameReader { get; set; }
        public string MiddleNameReader { get; set; }
        public int IdAddress { get; set; }
        public string NumberPhone { get; set; }
        public string HomePhone { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public byte[] PhotoReader { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReaderCardFile> ReaderCardFile { get; set; }
    }
}
